<?php

/**
 * @file
 * Contains field_group_background_and_link.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_group_background_and_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the field_group_background_and_link module.
    case 'help.page.field_group_background_and_link':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Field Group Background Image, Background Color and Link') . '</p>';
      return $output;

    default:
  }
}
